### ISSUE TITLE
Please update outdated flutter_svg 

### ISSUE THREAD

**Issue by Muhammad-Tayab** [Ademking/koukicons_flutter#8]
Because koukicons 2.0.2 depends on flutter_svg ^0.15.0 and no versions of koukicons match >2.0.2 <3.0.0, koukicons ^2.0.2 requires flutter_svg ^0.15.0.

I upgrade my flutter_svg to ^0.17.4

**Comment by Ademking** [comment]
I will update it soon... sorry for that

**Comment by Ademking** [comment]
@Muhammad-Tayab It's updated now.
